---
name: Helm Tests
on:
  push:
    paths:
      - 'deploy/helm/**'
  pull_request:
    paths:
      - 'deploy/helm/**'
  # Allows you to run this workflow manually
  workflow_dispatch:
jobs:
  check-for-doc-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make
        shell: bash
      - name: Regenerate Helm Docs
        run: |
          make helm > /dev/null # we don't actually need to output, just the results
          if ! git diff --exit-code; then
            echo "Helm docs are out of date. Please run 'make -C deploy/helm docs' and commit the changes."
            exit 1
          fi
        shell: bash
